#!/usr/bin/env python3

#Copyright (C) 2008-2011 by Benedict Paten (benedictpaten@gmail.com)
#
#Released under the MIT license, see LICENSE.txt

[build-system]
requires = [
    "setuptools",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "ortheus"
version = "0.5.0"
authors = [
    {name = "Benedict Paten"},
]
description = "Software for aligning and reconstructing indel histories (with Ensembl Compara modifications)"
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dynamic = [
    "readme",
]
license = "MIT"
requires-python = ">= 3.10"

[project.optional-dependencies]
test = [
    "sonLib@git+https://github.com/ComparativeGenomicsToolkit/sonLib.git@4380b09fcb452128b82815511f86ec305470213d#egg=sonLib",
]

[project.scripts]
"ortheus_core" = "ortheus.cli.ortheus_core:main"
"Ortheus.py" = "ortheus.cli.Ortheus:main"

[tool.setuptools.dynamic]
readme = {file = ["README.md"]}

[tool.setuptools.packages.find]
where = ["src"]
include = ["ortheus*"]
